In [1]:
from sensorium_2023.sensorium.datasets.mouse_video_loaders import mouse_video_loader

import numpy as np

In [17]:
mouseKey = "dynamic29623-4-9-Video-9b4f6a1a067fe51e15306b9628efea20"

dataPath = "../sensorium_data/"

path = [
    dataPath + mouseKey + "/"
]

device = 'cuda'

dataLoaders = mouse_video_loader(
    paths=path,
    batch_size=16,
    scale=1,
    max_frame=None,
    frames=60, # frames has to be > 50. If it fits on your gpu, we recommend 150
    offset=-1,
    include_behavior=True,
    include_pupil_centers=True,
    cuda=device!='cpu',
)

In [5]:
dataLoaders.keys()

dict_keys(['oracle', 'final_test_main', 'final_test_bonus', 'live_test_main', 'train', 'live_test_bonus'])

In [11]:
dataName = ""
for key in dataLoaders["train"].keys():
    dataName = key
dataName

'dynamic29623-4-9-Video-9b4f6a1a067fe51e15306b9628efea20'

In [16]:
dataLoaders["train"][dataName]

In [29]:
# [index][XYZ]
coordinates = np.load(dataPath + mouseKey + "/meta/neurons/cell_motor_coordinates.npy")
coordinates.shape

(7908, 3)

In [32]:
# [index][time]
responses = np.load(dataPath + mouseKey + "/data/responses/0.npy")
responses.shape

(7908, 325)

In [34]:
# [height][width][time]
videos = np.load(dataPath + mouseKey + "/data/videos/0.npy")
videos.shape

(36, 64, 325)

In [36]:
import neuralpredictors
neuralpredictors.__file__

'D:\\Users\\divad\\miniconda3\\envs\\py38\\lib\\site-packages\\neuralpredictors\\__init__.py'

In [2]:
import torch
seed = 42
from torch import nn

# With square kernels and equal stride
inputChannelCount = 1
outputChannelCount = 1
kernelSize = 2

input = torch.randn(2, inputChannelCount, 3, 3, 3)

torch.manual_seed(seed)
m = nn.Conv3d(inputChannelCount, outputChannelCount, kernelSize, padding=(2, 1, 1))
output = m(input)
print(output)

torch.manual_seed(seed)
from MyConv3d import MyConv3d
a = MyConv3d(inputChannelCount, outputChannelCount, kernelSize, padding=(2, 1, 1))
b = a(input)
print(b)

tensor([[[[[ 0.3117,  0.3117,  0.3117,  0.3117],
           [ 0.3117,  0.3117,  0.3117,  0.3117],
           [ 0.3117,  0.3117,  0.3117,  0.3117],
           [ 0.3117,  0.3117,  0.3117,  0.3117]],

          [[ 0.2124,  0.3435,  0.1595,  0.4725],
           [ 0.2260,  0.1232,  0.3726,  0.4663],
           [ 0.4020,  0.4962,  0.0388,  0.3899],
           [ 0.3488,  0.3885,  0.1674,  0.3302]],

          [[ 0.6387, -0.3275,  0.6100,  0.0444],
           [ 0.3533, -0.2630, -0.3281,  0.1025],
           [ 0.7066,  0.0937, -0.5408,  0.3588],
           [ 0.5556,  0.7861,  0.7033,  0.2852]],

          [[ 1.1162, -0.4658,  1.2520,  0.1301],
           [ 0.6809,  1.3849,  0.0513,  1.1606],
           [ 0.6165,  0.9694,  0.0134,  0.3173],
           [ 0.6588,  0.5439, -0.1253,  0.2265]],

          [[ 0.3901, -0.0691,  0.4334,  0.3041],
           [-0.3699,  0.1724, -0.3935,  0.4511],
           [-0.4968, -0.0845, -0.4217, -0.0111],
           [ 0.1956,  0.4405,  0.3464,  0.1437]],

          

In [2]:
input[0]

tensor([[[[-0.6740, -0.2710, -0.2715],
          [-0.3297, -0.5498, -1.2978],
          [-0.5920,  0.0497,  1.5713]],

         [[-0.2916, -0.9973,  0.1972],
          [ 0.0674, -1.8194,  0.7509],
          [ 0.3027, -0.4425,  1.1743]],

         [[-0.6304,  0.5317,  0.9333],
          [ 0.9651, -0.9091,  0.5259],
          [ 0.3829, -0.3612,  0.0952]]]])

tensor([[[[1.1468, 1.1468],
          [1.1468, 1.1468]],

         [[1.1468, 1.1468],
          [1.1468, 1.1468]]]], grad_fn=<CopySlices>)


In [5]:
output

tensor([[[[ 1.4086,  1.3309],
          [ 0.0480, -0.5683]],

         [[-0.0818, -0.2164],
          [-0.5283,  0.1489]]]], grad_fn=<SqueezeBackward1>)

In [6]:
output - b

tensor([[[[1.2727, 1.2271],
          [0.5473, 0.2352]],

         [[0.5509, 0.6326],
          [0.4125, 0.4190]]]], grad_fn=<SubBackward0>)

In [9]:
output.shape

torch.Size([1, 2, 2, 2])

In [10]:
input

tensor([[[[-0.3453,  0.7976, -0.6352],
          [-0.3357, -1.0160,  1.2257],
          [ 0.0166,  1.2200, -1.7745]],

         [[ 0.1204,  1.2946, -0.0129],
          [ 1.6046,  0.8597,  0.0955],
          [-0.2830,  0.9254, -0.8677]],

         [[-0.1420,  0.5461,  0.1550],
          [-1.1624,  0.4973, -0.2556],
          [-0.7221,  0.1805, -0.1423]]]])

In [11]:
output

tensor([[[[ 0.3472, -0.2566],
          [-0.0701, -0.0668]],

         [[-0.3615,  0.1715],
          [-0.3272,  0.1298]]]], grad_fn=<SqueezeBackward1>)

In [5]:
import MyConv3d
import torch
t1 = torch.randn(2, 2, 2)
t2 = torch.randn(2, 2, 2)
output1 = MyConv3d._cross_correlation_3d(t1, t2)
output1.shape
# import torch.nn.functional as F
# output2 = F.conv3d(t1, t2)

(2, 2, 2)
(2, 2, 2)
(7, 7, 7)
torch.Size([7, 7, 7])


torch.Size([7, 7, 7])

In [11]:
d = torch.randn(2, 2, 2)
d

tensor([[[ 1.5843,  0.1467],
         [-0.5280,  1.8272]],

        [[-1.5803, -0.5843],
         [ 1.2177, -0.0532]]])

In [12]:
d[:][0][:]

tensor([[ 1.5843,  0.1467],
        [-0.5280,  1.8272]])

In [13]:
d[0][:][:]

tensor([[ 1.5843,  0.1467],
        [-0.5280,  1.8272]])

In [19]:
d[...][:][0]

tensor([[ 1.5843,  0.1467],
        [-0.5280,  1.8272]])

In [6]:
import torch
import torch.nn.functional as F

# Example 4D tensors (volumes)
tensor1 = torch.rand(1, 2, 5, 5, 5)  # Shape: [batch_size, channels, depth, height, width]
tensor2 = torch.rand(1, 2, 3, 3, 3)  # Shape: [batch_size, channels, kernel_depth, kernel_height, kernel_width]

# Apply 4D cross-correlation using conv3d
result = F.conv3d(tensor1, tensor2)

print("4D Cross-correlation result:", result.shape)


4D Cross-correlation result: torch.Size([1, 1, 3, 3, 3])
